# Application Configuration
spring.application.name=train-reservation-system
server.port=8080

# Active profile
spring.profiles.active=dev

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC

# Error Handling
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param
server.error.include-exception=false
